name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Node.js
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify Node.js 20

      # Deploy to Nginx server
      - name: Deploy to Nginx server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # Use SSH key instead of password
          debug: true
          # script: |
          #   cd pms

          #   echo "Installing npm dependencies..."
          #   npm install
            
          #   echo "Building the application..."
          #   npm run build
            
          #   echo "Restarting PM2 processes..."
          #   pm2 restart all
